# Generated by Django 6.0.6 on 2026-06-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizze'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['position'], 'verbose_name': 'Quizfrage', 'verbose_name_plural': 'Quizfragen'},
        ),
    ]
